[phases.setup]
nixPkgs = ['nodejs-20_x', 'python312']
aptPkgs = ['build-essential', 'libudev-dev']
providers = ["node", "python"]

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = "npm run start"
